### ISSUE TITLE
Another Athena cli

### ISSUE THREAD

**Issue by zzl0** [pengwynn/athena-cli#1]
Hello Wynn, it seems we have a common interest, I have also created an Athena CLI tool that can do auto-completion and syntax highlighting. Please try it out if you are interested in it.

https://github.com/dbcli/athenacli

**Comment by pengwynn** [comment]
Very nice, @zzl0. The autocomplete is an especially nice touch. Happy to link to it from README if you want to send over a patch.

**Comment by zzl0** [comment]
@pengwynn Thank you, I will send a PR for that.
